export enum MODAL_NAME {
  MOVIE_CREATE = 'MOVIE_CREATE',
  MOVIE_UPDATE = 'MOVIE_UPDATE',
  MOVIE_DELETE = 'MOVIE_DELETE',
  MOVIE_COMPARE_VIEW = 'MOVIE_COMPARE_VIEW',
  CATEGORY_CREATE = 'CATEGORY_CREATE',
}
